name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./source/premise_id.sln
    - name: Build
      run: dotnet build ./source/premise_id.sln --no-restore
    - name: Test
      run: dotnet test ./source/premise_id.sln --no-build --verbosity normal
